# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-tf-state-workshop-232c6cb36b7bf900"
    dynamodb_table = "dev_terraform_locks_."
    encrypt        = true
    key            = "./terraform_locks_..tfstate"
    region         = "eu-west-1"
  }
}
